# Generated by Django 4.0.2 on 2022-07-30 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('gander', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('pin', models.PositiveIntegerField()),
                ('state', models.CharField(choices=[('mumbai', 'mumbai'), ('pune', 'pune'), ('chhattisgarh', 'chhattisgarh'), ('j&k', 'j&k')], max_length=100)),
                ('mobile', models.PositiveIntegerField()),
                ('email', models.EmailField(max_length=100)),
                ('job_city', models.CharField(max_length=100)),
                ('profile', models.ImageField(blank=True, upload_to='profile')),
                ('myfile', models.FileField(blank=True, upload_to=True)),
            ],
        ),
    ]
